### ISSUE TITLE
Review release 2.0

### ISSUE THREAD

**Issue by rmetzger** [ververica/streaming-ledger#3]
Branch: https://github.com/ververica/streaming-ledger/tree/release-2.0
Maven staging repository: https://oss.sonatype.org/content/repositories/comververica-1001/

**Comment by rmetzger** [comment]
Once somebody gives me a 👍 , I'll release the files in the staging repo to maven central (where it will be immutable forever)

**Comment by sjwiesman** [comment]
👍 

- Ran `mvn verify`
- Executed examples
- Deployed a Job against the paralell runtime

Thank you for your help with this

**Comment by rmetzger** [comment]
Cool. Releasing now :)

**Comment by rmetzger** [comment]
Done: https://search.maven.org/search?q=ververica
